---
name: arch

on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: [armv7, aarch64, s390x, ppc64le]
        distro: [ubuntu18.04, ubuntu20.04, alpine_latest, fedora_latest]

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y gcc make git libopenblas-dev liblapack-dev
                ;;
              fedora*)
                dnf -y update
                dnf -y install gcc make git libopenblas-dev liblapack-dev
                ;;
              alpine*)
                apk update
                apk add gcc make git libopenblas-dev liblapack-dev
                ;;
            esac


          run: |
            make
            make test
            out/run_tests_direct
            out/run_tests_indirect

