---
name: Build

on: [push, pull_request]

defaults:
  strategy:
    fail-fast: false

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libopenblas-dev
      - run: make
      - run: make test
      - run: test/run_tests

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install openblas -y
      - run: make
      - run: make test
      - run: test/run_tests

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openblas
      - run: make
      - run: make test
      - run: test/run_tests

