---
name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: echo $(CC)
      - run: $(CC) src\scs.c -Iinclude
      - run: make USE_LAPACK=0
      - run: make test
      - run: test/run_tests

