---
name: CMake

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libopenblas-dev liblapack-dev
      - run: mkdir build
      - run: |
          cd build
          mkdir out
          cmake -DBUILD_TESTING=ON ..
          make
          make install
          ctest --output-on-failure
          cd ../docs/src/examples/
          gcc -I/usr/local/include/scs -L/usr/local/lib/ qp.c -o qp.out -lscsdir
          ./qp.out

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openblas lapack
      - run: mkdir cmake_out
      - run: mkdir build
      - run: |
          cd build
          mkdir out
          cmake -DBUILD_TESTING=ON ..
          make
          make install
          ctest --output-on-failure
          cd ../docs/src/examples/
          gcc -I/usr/local/include/scs -L/usr/local/lib/ qp.c -o qp.out -lscsdir
          ./qp.out

