---
name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libopenblas-dev liblapack-dev
      - run: mkdir build 
      - run: cd build 
      - run: cmake -DBUILD_TESTING=ON ../
      - run: make
      - run: make install
      - run: ctest --output-on-failure

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openblas lapack
      - run: mkdir build 
      - run: cd build 
      - run: cmake -DBUILD_TESTING=ON ../
      - run: make
      - run: make install
      - run: ctest --output-on-failure

