---
name: Cmake

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libopenblas-dev liblapack-dev
      - run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON ..
          make
          make install
          ctest --output-on-failure

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openblas lapack
      - run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON ..
          make
          make install
          ctest --output-on-failure

