on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    - name: Build
			runs-on: ubuntu-latest
			steps:
				- uses: actions/checkout@v2
				- run: sudo apt-get update -y
				- run: sudo apt-get install -y libopenblas-dev liblapack-dev lcov
				- run: make test COVERAGE=1

		- name: Run tests
      - run: out/run_tests_direct    # test direct solver
      - run: out/run_tests_indirect  # test indirect solver

    - name: Process coverage
      uses: imciner2/run-lcov@v1
      with:
        input_directory: '${{ runner.workspace }}'
        output_file: '${{ runner.workspace }}/coverage.info'

		 - name: Upload coverage
			 if: ${{ matrix.coverage == 'ON' }}
			 uses: coverallsapp/github-action@master
			 with:
				 github-token: ${{ secrets.GITHUB_TOKEN }}
				 path-to-lcov: '${{ runner.workspace }}/coverage.info'

