name: Docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OS dependencies
        run: |
          sudo apt-get install doxygen
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install Python dependencies
        run: |
          pip install sphinx sphinx-rtd-theme breathe docutils
      - name: Build wasm
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk 
          ./emsdk install latest
          ./emsdk activate latest 
          source ./emsdk_env.sh
          cd ..
          make wasm
          cp out/scs.js docs/src/_static/
          cp out/scs.wasm docs/src/_static/
      - name: Build docs
        run: |
          cd docs/src && make docs && touch ../.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
  
  
