---
name: GPU

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
      - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
      - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
      - run: nvcc -V
      - run: sudo apt-get install libopenblas-dev liblapack-dev
      - run: make gpu
      - run: make test_gpu
      # - run: out/run_tests_gpu_indirect    # gpus not available yet

